USE EnglishShadowingDB;
GO

SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;

-- Replace the current Video Bank with the curated real-source list below.
-- The database stores YouTube source URLs and transcript JSON paths. Transcript
-- files are generated by tools/video-import/import_batch.py and must be reviewed
-- before changing source_review_status from pending to approved.

DECLARE @OldVideoBankLessons TABLE (lesson_id BIGINT PRIMARY KEY);
DECLARE @OldVideoBankSentences TABLE (sentence_id BIGINT PRIMARY KEY);

INSERT INTO @OldVideoBankLessons (lesson_id)
SELECT DISTINCT l.lesson_id
FROM Lessons AS l
INNER JOIN Courses AS c ON c.course_id = l.course_id
WHERE c.course_type = 'video_bank'
   OR c.title LIKE N'Video Bank%';

INSERT INTO @OldVideoBankSentences (sentence_id)
SELECT sentence_id
FROM Lesson_Sentences
WHERE lesson_id IN (SELECT lesson_id FROM @OldVideoBankLessons);

IF OBJECT_ID(N'dbo.Practice_Attempts', N'U') IS NOT NULL
BEGIN
    IF OBJECT_ID(N'dbo.Gamification_Ledger', N'U') IS NOT NULL
        DELETE FROM Gamification_Ledger
        WHERE attempt_id IN (
            SELECT attempt_id
            FROM Practice_Attempts
            WHERE sentence_id IN (SELECT sentence_id FROM @OldVideoBankSentences)
        );

    DELETE FROM Practice_Attempts
    WHERE sentence_id IN (SELECT sentence_id FROM @OldVideoBankSentences);
END

IF OBJECT_ID(N'dbo.Favorite_Sentences', N'U') IS NOT NULL
    DELETE FROM Favorite_Sentences
    WHERE sentence_id IN (SELECT sentence_id FROM @OldVideoBankSentences);

IF OBJECT_ID(N'dbo.Vocabulary_Items', N'U') IS NOT NULL
    DELETE FROM Vocabulary_Items
    WHERE source_sentence_id IN (SELECT sentence_id FROM @OldVideoBankSentences);

IF OBJECT_ID(N'dbo.Word_Error_Statistics', N'U') IS NOT NULL
    UPDATE Word_Error_Statistics
    SET last_sentence_id = NULL
    WHERE last_sentence_id IN (SELECT sentence_id FROM @OldVideoBankSentences);

IF OBJECT_ID(N'dbo.User_Sentence_Progress', N'U') IS NOT NULL
    DELETE FROM User_Sentence_Progress
    WHERE sentence_id IN (SELECT sentence_id FROM @OldVideoBankSentences);

IF OBJECT_ID(N'dbo.User_Lesson_Progress', N'U') IS NOT NULL
    DELETE FROM User_Lesson_Progress
    WHERE lesson_id IN (SELECT lesson_id FROM @OldVideoBankLessons);

IF OBJECT_ID(N'dbo.Practice_Sessions', N'U') IS NOT NULL
    DELETE FROM Practice_Sessions
    WHERE lesson_id IN (SELECT lesson_id FROM @OldVideoBankLessons);

DELETE FROM Lesson_Material
WHERE lesson_id IN (SELECT lesson_id FROM @OldVideoBankLessons);

DELETE FROM Lesson_Sentences
WHERE lesson_id IN (SELECT lesson_id FROM @OldVideoBankLessons);

DELETE FROM Lessons
WHERE lesson_id IN (SELECT lesson_id FROM @OldVideoBankLessons);

DELETE c
FROM Courses AS c
WHERE (c.course_type = 'video_bank' OR c.title LIKE N'Video Bank%')
  AND NOT EXISTS (SELECT 1 FROM Lessons AS l WHERE l.course_id = c.course_id);

DECLARE @VideoBankImports TABLE
(
    learning_mode VARCHAR(20) NOT NULL,
    course_title NVARCHAR(255) NOT NULL,
    course_level VARCHAR(20) NOT NULL,
    course_description NVARCHAR(MAX) NULL,
    lesson_order INT NOT NULL,
    title NVARCHAR(255) NOT NULL,
    description NVARCHAR(MAX) NULL,
    duration INT NOT NULL,
    video_url NVARCHAR(MAX) NOT NULL,
    source_id NVARCHAR(255) NOT NULL,
    transcript_url NVARCHAR(MAX) NOT NULL
);

INSERT INTO @VideoBankImports
    (learning_mode, course_title, course_level, course_description, lesson_order, title, description, duration, video_url, source_id, transcript_url)
VALUES
-- Life
('casual', N'Video Bank - Đời sống', 'Intermediate', N'Video về tâm lý học, các mối quan hệ và cách thấu hiểu bản thân.', 1, N'How to Tame a Pitiless Inner Critic', N'Cách chế ngự sự tự chỉ trích.', 0, N'https://www.youtube.com/watch?v=NU8v-f7KzRQ', N'NU8v-f7KzRQ', N'/media/video-bank/life-inner-critic/transcript.json'),
('casual', N'Video Bank - Đời sống', 'Intermediate', N'Video về tâm lý học, các mối quan hệ và cách thấu hiểu bản thân.', 2, N'How to Spot the Loveliest People in the World', N'Cách nhận ra những người đáng yêu nhất thế giới.', 0, N'https://www.youtube.com/watch?v=SvoO3OZPyb8', N'SvoO3OZPyb8', N'/media/video-bank/life-loveliest-people/transcript.json'),
('casual', N'Video Bank - Đời sống', 'Intermediate', N'Video về tâm lý học, các mối quan hệ và cách thấu hiểu bản thân.', 3, N'5 Ways to Spot Emotional Immaturity', N'5 dấu hiệu nhận biết sự thiếu trưởng thành về cảm xúc.', 0, N'https://www.youtube.com/watch?v=XdE17nu0zdo', N'XdE17nu0zdo', N'/media/video-bank/life-emotional-immaturity/transcript.json'),
('casual', N'Video Bank - Đời sống', 'Intermediate', N'Video về tâm lý học, các mối quan hệ và cách thấu hiểu bản thân.', 4, N'The 17 Secrets to a Successful Relationship', N'17 bí quyết cho một mối quan hệ thành công.', 0, N'https://www.youtube.com/watch?v=ak4j5pVHDGg', N'ak4j5pVHDGg', N'/media/video-bank/life-successful-relationship/transcript.json'),
('casual', N'Video Bank - Đời sống', 'Intermediate', N'Video về tâm lý học, các mối quan hệ và cách thấu hiểu bản thân.', 5, N'A Dark Way to Predict what might happen in your relationship', N'Một cách dự đoán những gì có thể xảy ra trong mối quan hệ của bạn.', 0, N'https://www.youtube.com/watch?v=znkBUxSMQ7s', N'znkBUxSMQ7s', N'/media/video-bank/life-predict-relationship/transcript.json'),
('casual', N'Video Bank - Đời sống', 'Intermediate', N'Video về tâm lý học, các mối quan hệ và cách thấu hiểu bản thân.', 6, N'The True and the False Self', N'Bản ngã chân thật và giả tạo.', 0, N'https://www.youtube.com/watch?v=A02Ucd6monY', N'A02Ucd6monY', N'/media/video-bank/life-true-false-self/transcript.json'),
('casual', N'Video Bank - Đời sống', 'Intermediate', N'Video về tâm lý học, các mối quan hệ và cách thấu hiểu bản thân.', 7, N'Learning to Forgive Ourselves', N'Học cách tha thứ cho chính mình.', 0, N'https://www.youtube.com/watch?v=YxKxi8iM-lw', N'YxKxi8iM-lw', N'/media/video-bank/life-forgive-ourselves/transcript.json'),

-- Academic
('academic', N'Video Bank - Học Thuật', 'Advanced', N'Video giải thích khoa học, lịch sử, y học và cơ thể người bằng hình ảnh sinh động.', 1, N'What staying up all night does to your brain', N'Thức trắng đêm ảnh hưởng thế nào đến não bộ?', 0, N'https://www.youtube.com/watch?v=idrbwnWLJ7w', N'idrbwnWLJ7w', N'/media/video-bank/academic-staying-up-all-night-brain/transcript.json'),
('academic', N'Video Bank - Học Thuật', 'Advanced', N'Video giải thích khoa học, lịch sử, y học và cơ thể người bằng hình ảnh sinh động.', 2, N'What would happen if you didn''t drink water?', N'Điều gì sẽ xảy ra nếu bạn không uống nước?', 0, N'https://www.youtube.com/watch?v=9iMGFqMmUFs', N'9iMGFqMmUFs', N'/media/video-bank/academic-no-water/transcript.json'),
('academic', N'Video Bank - Học Thuật', 'Advanced', N'Video giải thích khoa học, lịch sử, y học và cơ thể người bằng hình ảnh sinh động.', 3, N'How stress affects your body', N'Căng thẳng ảnh hưởng đến cơ thể bạn như thế nào.', 0, N'https://www.youtube.com/watch?v=v-t1Z5-oPtU', N'v-t1Z5-oPtU', N'/media/video-bank/academic-stress-body/transcript.json'),
('academic', N'Video Bank - Học Thuật', 'Advanced', N'Video giải thích khoa học, lịch sử, y học và cơ thể người bằng hình ảnh sinh động.', 4, N'The science of spiciness', N'Khoa học về vị cay.', 0, N'https://www.youtube.com/watch?v=qD0_yWgifDM', N'qD0_yWgifDM', N'/media/video-bank/academic-science-spiciness/transcript.json'),
('academic', N'Video Bank - Học Thuật', 'Advanced', N'Video giải thích khoa học, lịch sử, y học và cơ thể người bằng hình ảnh sinh động.', 5, N'How does your body know what time it is?', N'Cơ thể bạn làm sao biết bây giờ là mấy giờ?', 0, N'https://www.youtube.com/watch?v=Y8ZXOfWUbms', N'Y8ZXOfWUbms', N'/media/video-bank/academic-body-time/transcript.json'),
('academic', N'Video Bank - Học Thuật', 'Advanced', N'Video giải thích khoa học, lịch sử, y học và cơ thể người bằng hình ảnh sinh động.', 6, N'The mysterious life and death of Rasputin', N'Cuộc đời và cái chết bí ẩn của Rasputin.', 0, N'https://www.youtube.com/watch?v=4dEf1ep3O9I', N'4dEf1ep3O9I', N'/media/video-bank/academic-rasputin/transcript.json'),
('academic', N'Video Bank - Học Thuật', 'Advanced', N'Video giải thích khoa học, lịch sử, y học và cơ thể người bằng hình ảnh sinh động.', 7, N'Debunking the myth of the Lost Cause', N'Lật tẩy lầm tưởng về The Lost Cause trong lịch sử Mỹ.', 0, N'https://www.youtube.com/watch?v=XP0_wnaW-a0', N'XP0_wnaW-a0', N'/media/video-bank/academic-lost-cause/transcript.json'),

-- Work / Career
('professional', N'Video Bank - Professional', 'Advanced', N'Video về quản trị, chiến lược kinh doanh và phát triển sự nghiệp.', 1, N'How to Get People to Listen to You', N'Cách để khiến người khác lắng nghe bạn.', 0, N'https://www.youtube.com/watch?v=7AS94R-7YCs', N'7AS94R-7YCs', N'/media/video-bank/work-people-listen/transcript.json'),
('professional', N'Video Bank - Professional', 'Advanced', N'Video về quản trị, chiến lược kinh doanh và phát triển sự nghiệp.', 2, N'A Plan Is Not a Strategy', N'Kế hoạch không phải là một chiến lược.', 0, N'https://www.youtube.com/watch?v=iuYlGRnC7J8', N'iuYlGRnC7J8', N'/media/video-bank/work-plan-not-strategy/transcript.json'),
('professional', N'Video Bank - Professional', 'Advanced', N'Video về quản trị, chiến lược kinh doanh và phát triển sự nghiệp.', 3, N'What Is Strategy? It''s a Lot Simpler Than You Think', N'Chiến lược là gì? Nó đơn giản hơn bạn nghĩ nhiều.', 0, N'https://www.youtube.com/watch?v=o7Ik1OB4TaE', N'o7Ik1OB4TaE', N'/media/video-bank/work-what-is-strategy/transcript.json'),
('professional', N'Video Bank - Professional', 'Advanced', N'Video về quản trị, chiến lược kinh doanh và phát triển sự nghiệp.', 4, N'How to know if it''s time to change careers', N'Làm sao để biết đã đến lúc cần đổi nghề.', 0, N'https://www.youtube.com/watch?v=_8vLkIj_Lsk', N'_8vLkIj_Lsk', N'/media/video-bank/work-change-careers/transcript.json'),
('professional', N'Video Bank - Professional', 'Advanced', N'Video về quản trị, chiến lược kinh doanh và phát triển sự nghiệp.', 5, N'Emotional intelligence at work: Why IQ isn''t everything', N'Trí tuệ cảm xúc trong công việc: Tại sao IQ không phải là tất cả.', 0, N'https://www.youtube.com/watch?v=7ngIFlmRRPQ', N'7ngIFlmRRPQ', N'/media/video-bank/work-emotional-intelligence/transcript.json'),
('professional', N'Video Bank - Professional', 'Advanced', N'Video về quản trị, chiến lược kinh doanh và phát triển sự nghiệp.', 6, N'A Harvard career coach''s unspoken rules for getting promoted', N'Quy tắc ngầm để thăng tiến từ một huấn luyện viên sự nghiệp Harvard.', 0, N'https://www.youtube.com/watch?v=n8aA3DfiVuE', N'n8aA3DfiVuE', N'/media/video-bank/work-unspoken-rules-promoted/transcript.json'),
('professional', N'Video Bank - Professional', 'Advanced', N'Video về quản trị, chiến lược kinh doanh và phát triển sự nghiệp.', 7, N'The lost art of accomplishment without burnout', N'Nghệ thuật đạt thành tựu mà không bị kiệt sức.', 0, N'https://www.youtube.com/watch?v=0HMjTxKRbaI', N'0HMjTxKRbaI', N'/media/video-bank/work-accomplishment-no-burnout/transcript.json');

DECLARE
    @ImportMode VARCHAR(20),
    @ImportCourseTitle NVARCHAR(255),
    @ImportCourseLevel VARCHAR(20),
    @ImportCourseDescription NVARCHAR(MAX),
    @ImportLessonOrder INT,
    @ImportTitle NVARCHAR(255),
    @ImportDescription NVARCHAR(MAX),
    @ImportDuration INT,
    @ImportVideoUrl NVARCHAR(MAX),
    @ImportSourceId NVARCHAR(255),
    @ImportTranscriptUrl NVARCHAR(MAX),
    @ImportCourseId BIGINT,
    @ImportLessonId BIGINT;

DECLARE VideoBankImportCursor CURSOR LOCAL FAST_FORWARD FOR
SELECT learning_mode, course_title, course_level, course_description, lesson_order, title, description, duration, video_url, source_id, transcript_url
FROM @VideoBankImports
ORDER BY learning_mode, lesson_order;

OPEN VideoBankImportCursor;
FETCH NEXT FROM VideoBankImportCursor INTO
    @ImportMode, @ImportCourseTitle, @ImportCourseLevel, @ImportCourseDescription,
    @ImportLessonOrder, @ImportTitle, @ImportDescription, @ImportDuration,
    @ImportVideoUrl, @ImportSourceId, @ImportTranscriptUrl;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @ImportCourseId = NULL;
    SET @ImportLessonId = NULL;

    IF NOT EXISTS (SELECT 1 FROM Courses WHERE title = @ImportCourseTitle AND learning_mode = @ImportMode)
    BEGIN
        INSERT INTO Courses (title, [description], level, learning_mode, course_type)
        VALUES (@ImportCourseTitle, @ImportCourseDescription, @ImportCourseLevel, @ImportMode, 'video_bank');
        SET @ImportCourseId = SCOPE_IDENTITY();
    END
    ELSE
    BEGIN
        SELECT @ImportCourseId = course_id
        FROM Courses
        WHERE title = @ImportCourseTitle AND learning_mode = @ImportMode;

        UPDATE Courses
        SET [description] = @ImportCourseDescription,
            level = @ImportCourseLevel,
            course_type = 'video_bank'
        WHERE course_id = @ImportCourseId;
    END

    INSERT INTO Lessons (course_id, title, [description], lesson_order, duration)
    VALUES (@ImportCourseId, @ImportTitle, @ImportDescription, @ImportLessonOrder, @ImportDuration);
    SET @ImportLessonId = SCOPE_IDENTITY();

    INSERT INTO Lesson_Material
        (lesson_id, material_type, content_url, source_provider, source_id, license_note, source_review_status)
    VALUES
        (@ImportLessonId, 'video', @ImportVideoUrl, N'youtube', @ImportSourceId, N'Real video source. Review source ownership/license before public classroom use.', 'pending'),
        (@ImportLessonId, 'transcript', @ImportTranscriptUrl, N'youtube', @ImportSourceId, N'Manual captions imported with yt-dlp when available. Review caption quality before approving.', 'pending');

    FETCH NEXT FROM VideoBankImportCursor INTO
        @ImportMode, @ImportCourseTitle, @ImportCourseLevel, @ImportCourseDescription,
        @ImportLessonOrder, @ImportTitle, @ImportDescription, @ImportDuration,
        @ImportVideoUrl, @ImportSourceId, @ImportTranscriptUrl;
END

CLOSE VideoBankImportCursor;
DEALLOCATE VideoBankImportCursor;

-- Replace broken/duplicate curriculum seeds with the real grade 6-9 audio lessons.
DECLARE @OldCurriculumLessons TABLE (lesson_id BIGINT PRIMARY KEY);
DECLARE @OldCurriculumSentences TABLE (sentence_id BIGINT PRIMARY KEY);

INSERT INTO @OldCurriculumLessons (lesson_id)
SELECT DISTINCT l.lesson_id
FROM Lessons AS l
INNER JOIN Courses AS c ON c.course_id = l.course_id
LEFT JOIN Lesson_Material AS lm ON lm.lesson_id = l.lesson_id
WHERE c.course_type = 'curriculum'
   OR c.title LIKE N'Tiếng Anh lớp%'
   OR lm.content_url LIKE '/media/curriculum/%';

INSERT INTO @OldCurriculumSentences (sentence_id)
SELECT sentence_id
FROM Lesson_Sentences
WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons);

IF OBJECT_ID(N'dbo.Practice_Attempts', N'U') IS NOT NULL
BEGIN
    IF OBJECT_ID(N'dbo.Gamification_Ledger', N'U') IS NOT NULL
        DELETE FROM Gamification_Ledger
        WHERE attempt_id IN (
            SELECT attempt_id
            FROM Practice_Attempts
            WHERE sentence_id IN (SELECT sentence_id FROM @OldCurriculumSentences)
        );

    DELETE FROM Practice_Attempts
    WHERE sentence_id IN (SELECT sentence_id FROM @OldCurriculumSentences);
END

IF OBJECT_ID(N'dbo.Favorite_Sentences', N'U') IS NOT NULL
    DELETE FROM Favorite_Sentences
    WHERE sentence_id IN (SELECT sentence_id FROM @OldCurriculumSentences);

IF OBJECT_ID(N'dbo.Vocabulary_Items', N'U') IS NOT NULL
    DELETE FROM Vocabulary_Items
    WHERE source_sentence_id IN (SELECT sentence_id FROM @OldCurriculumSentences);

IF OBJECT_ID(N'dbo.Word_Error_Statistics', N'U') IS NOT NULL
    UPDATE Word_Error_Statistics
    SET last_sentence_id = NULL
    WHERE last_sentence_id IN (SELECT sentence_id FROM @OldCurriculumSentences);

IF OBJECT_ID(N'dbo.User_Sentence_Progress', N'U') IS NOT NULL
    DELETE FROM User_Sentence_Progress
    WHERE sentence_id IN (SELECT sentence_id FROM @OldCurriculumSentences);

IF OBJECT_ID(N'dbo.User_Lesson_Progress', N'U') IS NOT NULL
    DELETE FROM User_Lesson_Progress
    WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons);

IF OBJECT_ID(N'dbo.Practice_Sessions', N'U') IS NOT NULL
    DELETE FROM Practice_Sessions
    WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons);

IF OBJECT_ID(N'dbo.AI_Dialogue_Turns', N'U') IS NOT NULL
    DELETE FROM AI_Dialogue_Turns
    WHERE dialogue_session_id IN (
        SELECT dialogue_session_id
        FROM AI_Dialogue_Sessions
        WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons)
    );

IF OBJECT_ID(N'dbo.AI_Dialogue_Sessions', N'U') IS NOT NULL
    DELETE FROM AI_Dialogue_Sessions
    WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons);

DELETE FROM Lesson_Material
WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons);

DELETE FROM Lesson_Sentences
WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons);

DELETE FROM Lessons
WHERE lesson_id IN (SELECT lesson_id FROM @OldCurriculumLessons);

DELETE FROM Users_Courses
WHERE course_id IN (
    SELECT course_id
    FROM Courses
    WHERE course_type = 'curriculum'
       OR title LIKE N'Tiếng Anh lớp%'
);

DELETE FROM Courses
WHERE course_type = 'curriculum'
   OR title LIKE N'Tiếng Anh lớp%';

DECLARE @CurriculumImports TABLE
(
    course_title NVARCHAR(255) NOT NULL,
    course_level VARCHAR(20) NOT NULL,
    course_description NVARCHAR(MAX) NULL,
    lesson_order INT NOT NULL,
    title NVARCHAR(255) NOT NULL,
    description NVARCHAR(MAX) NULL,
    duration INT NOT NULL,
    transcript_url NVARCHAR(MAX) NOT NULL,
    audio_url NVARCHAR(MAX) NOT NULL
);

INSERT INTO @CurriculumImports
    (course_title, course_level, course_description, lesson_order, title, description, duration, transcript_url, audio_url)
VALUES
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 1, N'Unit 1: My New School', N'Audio and transcript for grade 6, unit 1.', 0, N'/media/curriculum/grade-6/unit-1/transcript.json', N'/media/curriculum/grade-6/unit-1/unit-1-getting-started-ex-1.wav'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 2, N'Unit 2: My House', N'Audio and transcript for grade 6, unit 2.', 0, N'/media/curriculum/grade-6/unit-2/transcript.json', N'/media/curriculum/grade-6/unit-2/act1.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 3, N'Unit 3: My Friends', N'Audio and transcript for grade 6, unit 3.', 0, N'/media/curriculum/grade-6/unit-3/transcript.json', N'/media/curriculum/grade-6/unit-3/act1 (1).mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 4, N'Unit 4: My Neighbourhood', N'Audio and transcript for grade 6, unit 4.', 0, N'/media/curriculum/grade-6/unit-4/transcript.json', N'/media/curriculum/grade-6/unit-4/20201130-tienganh6-kntt-b1-23.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 5, N'Unit 5: Natural Wonders of Viet Nam', N'Audio and transcript for grade 6, unit 5.', 0, N'/media/curriculum/grade-6/unit-5/transcript.json', N'/media/curriculum/grade-6/unit-5/act1-4-.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 6, N'Unit 6: Our Tet Holiday', N'Audio and transcript for grade 6, unit 6.', 0, N'/media/curriculum/grade-6/unit-6/transcript.json', N'/media/curriculum/grade-6/unit-6/act1-7-.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 7, N'Unit 7: Television', N'Audio and transcript for grade 6, unit 7.', 0, N'/media/curriculum/grade-6/unit-7/transcript.json', N'/media/curriculum/grade-6/unit-7/u7-getting-ex1.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 8, N'Unit 8: Sports and Games', N'Audio and transcript for grade 6, unit 8.', 0, N'/media/curriculum/grade-6/unit-8/transcript.json', N'/media/curriculum/grade-6/unit-8/tieng-anh-6-tap-2-global-success-unit-8-sports-and-games-getting-started-1-listen-and-read-sach-mem.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 9, N'Unit 9: Cities of the World', N'Audio and transcript for grade 6, unit 9.', 0, N'/media/curriculum/grade-6/unit-9/transcript.json', N'/media/curriculum/grade-6/unit-9/gs-u9-ex1.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 10, N'Unit 10: Our Houses in the Future', N'Audio and transcript for grade 6, unit 10.', 0, N'/media/curriculum/grade-6/unit-10/transcript.json', N'/media/curriculum/grade-6/unit-10/gs-u10-getting-started-ex1.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 11, N'Unit 11: Our Greener World', N'Audio and transcript for grade 6, unit 11.', 0, N'/media/curriculum/grade-6/unit-11/transcript.json', N'/media/curriculum/grade-6/unit-11/gs-u11-getting-started-ex1.mp3'),
(N'Tiếng Anh lớp 6', 'Beginner', N'Giáo trình tiếng Anh lớp 6 với audio và transcript theo từng unit.', 12, N'Unit 12: Robots', N'Audio and transcript for grade 6, unit 12.', 0, N'/media/curriculum/grade-6/unit-12/transcript.json', N'/media/curriculum/grade-6/unit-12/gs-u12-getting-started-ex1.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 1, N'Unit 1: Hobbies', N'Audio and transcript for grade 7, unit 1.', 0, N'/media/curriculum/grade-7/unit-1/transcript.json', N'/media/curriculum/grade-7/unit-1/002.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 2, N'Unit 2: Healthy Living', N'Audio and transcript for grade 7, unit 2.', 0, N'/media/curriculum/grade-7/unit-2/transcript.json', N'/media/curriculum/grade-7/unit-2/008.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 3, N'Unit 3: Community Service', N'Audio and transcript for grade 7, unit 3.', 0, N'/media/curriculum/grade-7/unit-3/transcript.json', N'/media/curriculum/grade-7/unit-3/014.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 4, N'Unit 4: Music and Arts', N'Audio and transcript for grade 7, unit 4.', 0, N'/media/curriculum/grade-7/unit-4/transcript.json', N'/media/curriculum/grade-7/unit-4/022.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 5, N'Unit 5: Food and Drink', N'Audio and transcript for grade 7, unit 5.', 0, N'/media/curriculum/grade-7/unit-5/transcript.json', N'/media/curriculum/grade-7/unit-5/030.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 6, N'Unit 6: A Visit to a School', N'Audio and transcript for grade 7, unit 6.', 0, N'/media/curriculum/grade-7/unit-6/transcript.json', N'/media/curriculum/grade-7/unit-6/038.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 7, N'Unit 7: Traffic', N'Audio and transcript for grade 7, unit 7.', 0, N'/media/curriculum/grade-7/unit-7/transcript.json', N'/media/curriculum/grade-7/unit-7/047.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 8, N'Unit 8: Films', N'Audio and transcript for grade 7, unit 8.', 0, N'/media/curriculum/grade-7/unit-8/transcript.json', N'/media/curriculum/grade-7/unit-8/054.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 9, N'Unit 9: Festivals around the World', N'Audio and transcript for grade 7, unit 9.', 0, N'/media/curriculum/grade-7/unit-9/transcript.json', N'/media/curriculum/grade-7/unit-9/061.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 10, N'Unit 10: Energy Sources', N'Audio and transcript for grade 7, unit 10.', 0, N'/media/curriculum/grade-7/unit-10/transcript.json', N'/media/curriculum/grade-7/unit-10/069.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 11, N'Unit 11: Travelling in the Future', N'Audio and transcript for grade 7, unit 11.', 0, N'/media/curriculum/grade-7/unit-11/transcript.json', N'/media/curriculum/grade-7/unit-11/075.mp3'),
(N'Tiếng Anh lớp 7', 'Intermediate', N'Giáo trình tiếng Anh lớp 7 với audio và transcript theo từng unit.', 12, N'Unit 12: English-Speaking Countries', N'Audio and transcript for grade 7, unit 12.', 0, N'/media/curriculum/grade-7/unit-12/transcript.json', N'/media/curriculum/grade-7/unit-12/082.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 1, N'Unit 1: Leisure time', N'Audio and transcript for grade 8, unit 1.', 0, N'/media/curriculum/grade-8/unit-1/transcript.json', N'/media/curriculum/grade-8/unit-1/track-1.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 2, N'Unit 2: Life in the countryside', N'Audio and transcript for grade 8, unit 2.', 0, N'/media/curriculum/grade-8/unit-2/transcript.json', N'/media/curriculum/grade-8/unit-2/track-7.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 3, N'Unit 3: Teenagers', N'Audio and transcript for grade 8, unit 3.', 0, N'/media/curriculum/grade-8/unit-3/transcript.json', N'/media/curriculum/grade-8/unit-3/track-13_1.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 4, N'Unit 4: Ethnic groups of Viet Nam', N'Audio and transcript for grade 8, unit 4.', 0, N'/media/curriculum/grade-8/unit-4/transcript.json', N'/media/curriculum/grade-8/unit-4/track-20.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 5, N'Unit 5: Our customs and traditions', N'Audio and transcript for grade 8, unit 5.', 0, N'/media/curriculum/grade-8/unit-5/transcript.json', N'/media/curriculum/grade-8/unit-5/track-26.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 6, N'Unit 6: Lifestyles', N'Audio and transcript for grade 8, unit 6.', 0, N'/media/curriculum/grade-8/unit-6/transcript.json', N'/media/curriculum/grade-8/unit-6/track-32.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 7, N'Unit 7: Environmental protection', N'Audio and transcript for grade 8, unit 7.', 0, N'/media/curriculum/grade-8/unit-7/transcript.json', N'/media/curriculum/grade-8/unit-7/track-40.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 8, N'Unit 8: Shopping', N'Audio and transcript for grade 8, unit 8.', 0, N'/media/curriculum/grade-8/unit-8/transcript.json', N'/media/curriculum/grade-8/unit-8/track-46.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 9, N'Unit 9: Natural disasters', N'Audio and transcript for grade 8, unit 9.', 0, N'/media/curriculum/grade-8/unit-9/transcript.json', N'/media/curriculum/grade-8/unit-9/51.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 10, N'Unit 10: Communication in the future', N'Audio and transcript for grade 8, unit 10.', 0, N'/media/curriculum/grade-8/unit-10/transcript.json', N'/media/curriculum/grade-8/unit-10/unit-10.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 11, N'Unit 11: Science and technology', N'Audio and transcript for grade 8, unit 11.', 0, N'/media/curriculum/grade-8/unit-11/transcript.json', N'/media/curriculum/grade-8/unit-11/track-68.mp3'),
(N'Tiếng Anh lớp 8', 'Intermediate', N'Giáo trình tiếng Anh lớp 8 với audio và transcript theo từng unit.', 12, N'Unit 12: Life on other planets', N'Audio and transcript for grade 8, unit 12.', 0, N'/media/curriculum/grade-8/unit-12/transcript.json', N'/media/curriculum/grade-8/unit-12/track-74.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 1, N'Unit 1: Local community', N'Audio and transcript for grade 9, unit 1.', 0, N'/media/curriculum/grade-9/unit-1/transcript.json', N'/media/curriculum/grade-9/unit-1/ex1-getting-u1-ta9-global.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 2, N'Unit 2: City life', N'Audio and transcript for grade 9, unit 2.', 0, N'/media/curriculum/grade-9/unit-2/transcript.json', N'/media/curriculum/grade-9/unit-2/ex1-getting-u2-ta9-global.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 3, N'Unit 3: Healthy living for teens', N'Audio and transcript for grade 9, unit 3.', 0, N'/media/curriculum/grade-9/unit-3/transcript.json', N'/media/curriculum/grade-9/unit-3/ex1-getting-u3-ta9-global.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 4, N'Unit 4: Remembering the past', N'Audio and transcript for grade 9, unit 4.', 0, N'/media/curriculum/grade-9/unit-4/transcript.json', N'/media/curriculum/grade-9/unit-4/21.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 5, N'Unit 5: Our experiences', N'Audio and transcript for grade 9, unit 5.', 0, N'/media/curriculum/grade-9/unit-5/transcript.json', N'/media/curriculum/grade-9/unit-5/27.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 6, N'Unit 6: Vietnamese lifestyles: then and now', N'Audio and transcript for grade 9, unit 6.', 0, N'/media/curriculum/grade-9/unit-6/transcript.json', N'/media/curriculum/grade-9/unit-6/33.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 7, N'Unit 7: Natural wonders of the world', N'Audio and transcript for grade 9, unit 7.', 0, N'/media/curriculum/grade-9/unit-7/transcript.json', N'/media/curriculum/grade-9/unit-7/41.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 8, N'Unit 8: Tourism', N'Audio and transcript for grade 9, unit 8.', 0, N'/media/curriculum/grade-9/unit-8/transcript.json', N'/media/curriculum/grade-9/unit-8/47.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 9, N'Unit 9: World Englishes', N'Audio and transcript for grade 9, unit 9.', 0, N'/media/curriculum/grade-9/unit-9/transcript.json', N'/media/curriculum/grade-9/unit-9/53.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 10, N'Unit 10: Planet Earth', N'Audio and transcript for grade 9, unit 10.', 0, N'/media/curriculum/grade-9/unit-10/transcript.json', N'/media/curriculum/grade-9/unit-10/61.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 11, N'Unit 11: Electronic devices', N'Audio and transcript for grade 9, unit 11.', 0, N'/media/curriculum/grade-9/unit-11/transcript.json', N'/media/curriculum/grade-9/unit-11/67.mp3'),
(N'Tiếng Anh lớp 9', 'Advanced', N'Giáo trình tiếng Anh lớp 9 với audio và transcript theo từng unit.', 12, N'Unit 12: Career choices', N'Audio and transcript for grade 9, unit 12.', 0, N'/media/curriculum/grade-9/unit-12/transcript.json', N'/media/curriculum/grade-9/unit-12/73.mp3');

DECLARE
    @CurriculumCourseTitle NVARCHAR(255),
    @CurriculumCourseLevel VARCHAR(20),
    @CurriculumCourseDescription NVARCHAR(MAX),
    @CurriculumLessonOrder INT,
    @CurriculumTitle NVARCHAR(255),
    @CurriculumDescription NVARCHAR(MAX),
    @CurriculumDuration INT,
    @CurriculumTranscriptUrl NVARCHAR(MAX),
    @CurriculumAudioUrl NVARCHAR(MAX),
    @CurriculumCourseId BIGINT,
    @CurriculumLessonId BIGINT,
    @CurriculumSourceId NVARCHAR(255);

DECLARE CurriculumImportCursor CURSOR LOCAL FAST_FORWARD FOR
SELECT course_title, course_level, course_description, lesson_order, title, description, duration, transcript_url, audio_url
FROM @CurriculumImports
ORDER BY course_title, lesson_order;

OPEN CurriculumImportCursor;
FETCH NEXT FROM CurriculumImportCursor INTO
    @CurriculumCourseTitle, @CurriculumCourseLevel, @CurriculumCourseDescription,
    @CurriculumLessonOrder, @CurriculumTitle, @CurriculumDescription, @CurriculumDuration,
    @CurriculumTranscriptUrl, @CurriculumAudioUrl;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @CurriculumCourseId = NULL;
    SET @CurriculumLessonId = NULL;
    SET @CurriculumSourceId = REPLACE(REPLACE(@CurriculumTranscriptUrl, N'/media/curriculum/', N''), N'/transcript.json', N'');

    IF NOT EXISTS (SELECT 1 FROM Courses WHERE title = @CurriculumCourseTitle AND course_type = 'curriculum')
    BEGIN
        INSERT INTO Courses (title, [description], level, learning_mode, course_type)
        VALUES (@CurriculumCourseTitle, @CurriculumCourseDescription, @CurriculumCourseLevel, 'academic', 'curriculum');
        SET @CurriculumCourseId = SCOPE_IDENTITY();
    END
    ELSE
    BEGIN
        SELECT @CurriculumCourseId = course_id
        FROM Courses
        WHERE title = @CurriculumCourseTitle AND course_type = 'curriculum';
    END

    INSERT INTO Lessons (course_id, title, [description], lesson_order, duration)
    VALUES (@CurriculumCourseId, @CurriculumTitle, @CurriculumDescription, @CurriculumLessonOrder, @CurriculumDuration);
    SET @CurriculumLessonId = SCOPE_IDENTITY();

    INSERT INTO Lesson_Material
        (lesson_id, material_type, content_url, source_provider, source_id, license_note, source_review_status)
    VALUES
        (@CurriculumLessonId, 'transcript', @CurriculumTranscriptUrl, N'curriculum', @CurriculumSourceId, N'Curriculum transcript stored in repository media folder.', 'approved'),
        (@CurriculumLessonId, 'audio', @CurriculumAudioUrl, N'curriculum', @CurriculumSourceId, N'Curriculum audio stored in repository media folder.', 'approved');

    FETCH NEXT FROM CurriculumImportCursor INTO
        @CurriculumCourseTitle, @CurriculumCourseLevel, @CurriculumCourseDescription,
        @CurriculumLessonOrder, @CurriculumTitle, @CurriculumDescription, @CurriculumDuration,
        @CurriculumTranscriptUrl, @CurriculumAudioUrl;
END

CLOSE CurriculumImportCursor;
DEALLOCATE CurriculumImportCursor;

COMMIT TRANSACTION;
