// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShadowing.Data;

#nullable disable

namespace WebShadowing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619091606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebShadowing.Models.AiFeedback", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FeedbackId"));

                    b.Property<decimal?>("AccuracyScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("accuracy_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback_text");

                    b.Property<decimal?>("FluencyScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fluency_score");

                    b.Property<decimal?>("PronunciationScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("pronunciation_score");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("FeedbackId");

                    b.HasIndex("SessionId");

                    b.ToTable("AI_Feedback");
                });

            modelBuilder.Entity("WebShadowing.Models.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CourseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("WebShadowing.Models.Lesson", b =>
                {
                    b.Property<long>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LessonId"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("LessonOrder")
                        .HasColumnType("int")
                        .HasColumnName("lesson_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LessonId");

                    b.HasIndex("CourseId", "LessonOrder")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("WebShadowing.Models.LessonMaterial", b =>
                {
                    b.Property<long>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("material_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaterialId"));

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_url");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("material_type");

                    b.HasKey("MaterialId");

                    b.HasIndex("LessonId");

                    b.ToTable("Lesson_Material");
                });

            modelBuilder.Entity("WebShadowing.Models.PracticeSession", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("Practice_Sessions");
                });

            modelBuilder.Entity("WebShadowing.Models.Transcript", b =>
                {
                    b.Property<long>("TranscriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transcript_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TranscriptId"));

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<long>("RecordingId")
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transcript_text");

                    b.HasKey("TranscriptId");

                    b.HasIndex("RecordingId");

                    b.ToTable("Transcripts");
                });

            modelBuilder.Entity("WebShadowing.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebShadowing.Models.UserCourse", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_at");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Users_Courses");
                });

            modelBuilder.Entity("WebShadowing.Models.UserRecording", b =>
                {
                    b.Property<long>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("recording_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordingId"));

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.HasKey("RecordingId");

                    b.HasIndex("SessionId");

                    b.ToTable("User_Recordings");
                });

            modelBuilder.Entity("WebShadowing.Models.UserStatistic", b =>
                {
                    b.Property<long>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("stat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatId"));

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("average_score");

                    b.Property<DateTime?>("LastPracticeAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_practice_at");

                    b.Property<int>("StreakDays")
                        .HasColumnType("int")
                        .HasColumnName("streak_days");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int")
                        .HasColumnName("total_sessions");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("StatId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("User_Statistics");
                });

            modelBuilder.Entity("WebShadowing.Models.AiFeedback", b =>
                {
                    b.HasOne("WebShadowing.Models.PracticeSession", "Session")
                        .WithMany("AiFeedbacks")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WebShadowing.Models.Lesson", b =>
                {
                    b.HasOne("WebShadowing.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WebShadowing.Models.LessonMaterial", b =>
                {
                    b.HasOne("WebShadowing.Models.Lesson", "Lesson")
                        .WithMany("Materials")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("WebShadowing.Models.PracticeSession", b =>
                {
                    b.HasOne("WebShadowing.Models.Lesson", "Lesson")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShadowing.Models.User", "User")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShadowing.Models.Transcript", b =>
                {
                    b.HasOne("WebShadowing.Models.UserRecording", "Recording")
                        .WithMany("Transcripts")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("WebShadowing.Models.UserCourse", b =>
                {
                    b.HasOne("WebShadowing.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShadowing.Models.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShadowing.Models.UserRecording", b =>
                {
                    b.HasOne("WebShadowing.Models.PracticeSession", "Session")
                        .WithMany("Recordings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WebShadowing.Models.UserStatistic", b =>
                {
                    b.HasOne("WebShadowing.Models.User", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("WebShadowing.Models.UserStatistic", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShadowing.Models.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("WebShadowing.Models.Lesson", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("PracticeSessions");
                });

            modelBuilder.Entity("WebShadowing.Models.PracticeSession", b =>
                {
                    b.Navigation("AiFeedbacks");

                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("WebShadowing.Models.User", b =>
                {
                    b.Navigation("PracticeSessions");

                    b.Navigation("Statistics");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("WebShadowing.Models.UserRecording", b =>
                {
                    b.Navigation("Transcripts");
                });
#pragma warning restore 612, 618
        }
    }
}
